version: "3.8"

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017

    server:
        image: node:lts-alpine
        working_dir: /usr/src/app
        command: npm run start
        environment:
            PORT: 3000
            DATABASE_URL: mongodb://mongo:27017/characters
        volumes:
            - ./server:/usr/src/app
        ports:
            - 3000:3000

    client:
        image: node:lts-alpine
        working_dir: /usr/src/app
        command: npm run serve
        volumes:
            - ./client:/usr/src/app
        ports:
            - 8080:8080
